# Generated by Django 2.1 on 2018-10-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreference',
            name='mc_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
