# Generated by Django 2.1 on 2018-09-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('india', 'India'), ('bangladesh', 'Bangladesh'), ('nepal', 'Nepal'), ('bhutan', 'Bhutan'), ('usa', 'United States of America'), ('uk', 'United Kingdom'), ('france', 'France'), ('italy', 'Italy'), ('spain', 'Spain'), ('japan', 'Japan')], default='India', max_length=120),
        ),
    ]
